services:
  - type: web
    name: imagetotext
    env: rust
    buildCommand: |
      # Install system dependencies
      apt-get update -y
      apt-get install -y build-essential
      apt-get install -y pkg-config
      apt-get install -y libleptonica-dev
      apt-get install -y tesseract-ocr
      apt-get install -y libtesseract-dev
      # Set PKG_CONFIG_PATH
      export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
      # Verify leptonica is properly installed
      pkg-config --libs lept || echo "Leptonica not found in pkg-config"
      # Build the Rust application
      cargo build --release
    startCommand: ./target/release/imagetotext
    envVars:
      - key: RUST_LOG
        value: info
      - key: PKG_CONFIG_PATH
        value: /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig
      - key: LD_LIBRARY_PATH
        value: /usr/lib/x86_64-linux-gnu 