services:
  - type: web
    name: imagetotext
    env: rust
    buildPacks:
      - type: apt
        packages: build-essential pkg-config libleptonica-dev tesseract-ocr libtesseract-dev
    buildCommand: "export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig && cargo build --release"
    startCommand: "./target/release/imagetotext"
    envVars:
      - key: RUST_LOG
        value: info
      - key: RENDER
        value: "true" 