services:
  - type: web
    name: imagetotext
    env: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/imagetotext
    envVars:
      - key: RUST_LOG
        value: info
      - key: RENDER
        value: "true" 